version: "3.9"
services:
  frontend:
      build: ./frontend
      ports:
        - "8001:80"
      depends_on:
        - backend
  backend:
    build:
      context: ./backend
      args:
        DATABASE_URL: ${DATABASE_URL}  # Build argument
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}   # Runtime environment variable
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=useradmin
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_DB=trainingdb
