version: "3.9"
services:
  backend:
    build:
      context: ./backend
      args:
        DATABASE_URL: ${DATABASE_URL}  # Build argument
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}   # Runtime environment variable
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=useradmin
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_DB=trainingdb
